### ISSUE TITLE
Device is Not visible to Amazon Echo

### ISSUE THREAD

**Issue by cmeans** [smartthings-users/device-type.nest#36]
How do I expose the device so I can control it via Amazon Echo?  When I try to configure the list of devices that the Echo is allowed to control, the Nest isn't an option.

It would be *_really *_nice to be able to control it via the Amazon Echo

**Comment by cmeans** [comment]
Though I was able to expose the Nest to IFTTT, I'm unable to set it to Away/Present via a Recipe.

**Comment by chrispauly** [comment]
Amazon now enabled the ability to deal with any Thermostat device on your SmartThings hub.  https://blog.smartthings.com/news/smartthings-updates/alexa-turn-up-the-heat/

**Comment by cmeans** [comment]
Thanks, but I believe that functionality is still more limited than I need.  I was able to get the functionality I needed via the Rule Machine and a tweak to the Nest device type code.
